CC=g++
CFLAGS=-I.
DEPS = packet.h # header file 
OBJ = sender.o
OBJJ = receiver.o
MAKE = make

%.o: %.cpp $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

all:	sender receiver

sender: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)

receiver: $(OBJJ)
	  $(CC) -o $@ $^ $(CFLAGS)

clean:
	$(RM) sender
	$(RM) sender.o
	$(RM) receiver
	$(RM) receiver.o